Feature/2871 16 remove alternating rows of table
brightlayer-ui/react-themes pull request #25
Opened 2022-02-01 11:16 UTC by bkarambe

Fixes #16 

#### Changes proposed in this Pull Request:
- Removed alternate table row colors styles

#### Screenshots:
<img width="1792" alt="Screenshot 2022-02-01 at 4 43 44 PM" src="https://user-images.githubusercontent.com/25982779/151958752-ab7eab0a-2990-405f-a236-4dd47242dd99.png">

#### To Test:
- yarn start
- Open Material Components --> Data Display --> Table

2022-02-01 13:48 UTC, jeffvg approved these changes

2022-02-03 17:30 UTC, huayunh approved these changes

2022-02-03 17:30 UTC, huayunh commented on CommonOverrides.md
> +## Zebra Striping Table
I like this doc! I think it is a great idea.

2022-02-03 17:30 UTC, huayunh commented on CommonOverrides.md
> +## Zebra Striping Table
Can consider adding an image to explain the difference too.

2022-02-03 17:30 UTC, huayunh commented on CommonOverrides.md
> +            .mix(Color(MediumBlackBackground), 0.5)
```suggestion
```ts
import Color from 'color';
import * as BLUIColors from '@brightlayer-ui/colors';
...

"&:nth-of-type(odd):not($selected)": {
    backgroundColor: BLUIColors.darkBlack[300],
    "&$hover:hover": {
        backgroundColor: Color(BLUIColors.darkBlack[300])
            .mix(Color(MediumBlackBackground), 0.5)
```

2022-02-03 17:30 UTC, huayunh commented on src/blueTheme.ts
> +                backgroundColor: ThemeColors.background.paper,
I would just drop this line here

2022-02-03 17:30 UTC, huayunh commented on src/blueDarkTheme.ts
> +                backgroundColor: ThemeColors.background.paper,
maybe drop this too.

2022-02-04 13:07 UTC, joebochill requested changes

2022-02-04 13:07 UTC, joebochill commented on CommonOverrides.md
> +}
You are referring to a bunch of variables in here that are not defined...

2022-02-04 13:09 UTC, joebochill commented on CommonOverrides.md
> +}
This needs to be an actual working example that someone could drop into their project (or it should be an example of how to put this override into the theme, in the createTheme function, if they want to use it everywhere throughout their app)

2022-02-08 13:35 UTC, joebochill reviewed
Example updates look good, we just need to make sure the colors are correct.

2022-02-08 13:35 UTC, joebochill commented on CommonOverrides.md
> +    <img width="100%" style="max-width: 600px" alt="Zebra Striping Table" src="./images/zebraStripingTable.png">
Can we change this image to use the actual recommended colors? This definitely looks like zebra stripes, but I don't think we want to be encouraging anyone to actually use colors like this.

2022-02-08 13:35 UTC, joebochill commented on CommonOverrides.md
> +            }
These are not the right colors...did you mix up light and dark theme values?

<img width="572" alt="image" src="https://user-images.githubusercontent.com/29152776/152996962-7e41401e-6289-4cab-98dc-be9657d2e28d.png">

2022-02-08 13:35 UTC, joebochill commented on CommonOverrides.md
> +                                },
Same thing here with the colors.

2022-02-08 21:24 UTC, jeffvg commented
looks good both light and dark theme

2022-02-09 15:54 UTC, joebochill approved these changes

2022-02-09 15:54 UTC, merged