Feature/v5 react themes
brightlayer-ui/react-themes pull request #33
Opened 2022-03-02 12:11 UTC by ektasawant

Fixes 2728

#### Changes proposed in this Pull Request:

- [ ] Migrate to MUIv5
- [ ] Update CSS for 
- [ ] Update bg color for valueLabelIcon valueLabelIcon
- [ ] Remove css for wrapper from tab https://github.com/mui/material-ui/pull/26926
- [ ] Update CSS for MuiAppbar dark theme.
- [ ] Remove badge overrides css from dark theme.

#### Screenshots:
<img width="1778" alt="Screenshot 2022-03-02 at 5 40 34 PM" src="https://user-images.githubusercontent.com/10433274/156359233-0393019c-1b12-4209-ab69-97d8f2f408d0.png">

<img width="1642" alt="Screenshot 2022-03-02 at 5 40 21 PM" src="https://user-images.githubusercontent.com/10433274/156359257-517c9f71-bdd8-4f27-94ef-b7a925bc1f5c.png">

#### To Test:
-

2022-03-04 16:34 UTC, joebochill reviewed
I did not go through with a fine toothed comb, but the code changes look pretty good in my quick scan. As long as somebody does a side-by-side of the old with the new and things look correct, then I think we're good.

2022-03-04 16:34 UTC, joebochill commented on package.json
> +        "@mui/styles": "^5.3.0"
Are these actually dependencies, or do they just need to be peerDependencies (I'm thinking probably the latter)

2022-03-04 16:34 UTC, joebochill commented on src/blueDarkTheme.ts
> +export const blueDarkTheme = createTheme({
this is fundamentally changing how our theme gets used (instead of just exporting the options and letting users call createTheme, we're now exporting the entire generated theme). Do we need to be doing this? How does this affect a user's ability to override/adjust theme values?

2022-03-04 16:34 UTC, joebochill commented on src/blueDarkTheme.ts
> +                    height: 6,
looks like we removed a lot of styles around the slider in here...does this still look the way we expect?

2022-03-04 16:34 UTC, joebochill commented on src/blueDarkTheme.ts
> +                        },
The 'completed' styles seem to be missing for the step icon

2022-03-04 16:34 UTC, joebochill commented on src/blueTheme.ts
> +                label: {},
Can we take these out now since we don't need them?

2022-03-04 16:34 UTC, joebochill commented on src/blueTheme.ts
> +                    },
These look like new styles that weren't there before...are they needed?

2022-03-04 18:39 UTC, huayunh commented
The theme transition and the input page seem to still eat up a lot of performance

# 1
Error outlined select field sometimes get the wrong color

https://user-images.githubusercontent.com/8997218/156818521-3211ea53-8e2b-40ea-ae08-e0075b675a0c.mov

# 2
Button toggle group under RTL is wrong (border on the wrong side)
![image](https://user-images.githubusercontent.com/8997218/156818731-6b1d58a2-f641-448a-8535-5c2865d92141.png)

# 3
I assume there's more to fix for the drawer rail, as the hamburger icon is misaligned
![image](https://user-images.githubusercontent.com/8997218/156818858-85167698-e2df-49f4-833d-9bd61035c9cd.png)

# 4
this is still getting the wrong color
![image](https://user-images.githubusercontent.com/8997218/156819179-ce168677-7140-4ea2-bbf0-3e78672c8e9e.png)

# 5
Chips
![image](https://user-images.githubusercontent.com/8997218/156819346-07bc0c7d-c51a-467e-8b00-9edeb0257309.png)

# 6 
I see that MUI now allows for additional component `color`s, like `color=success` etc. Can you either include those in, or maybe log an enhancement / story to include these checks for future? I logged a related design bug in #34

# 7 
This header is taking a different color
![image](https://user-images.githubusercontent.com/8997218/156819777-2cf191ec-9702-4d79-8fad-6fdb836af2a2.png)
expecting table cell / header to not have any background color

# 8 
Stepper, do not put white text on blue200. It is hard to read.
![image](https://user-images.githubusercontent.com/8997218/156821307-2ec036ce-ff09-4b88-a68d-0e51db11e15a.png)

Here's design in Figma
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/8997218/156821483-0a8d9775-a866-4e9e-a092-f297b5c2cc9b.png">

# 9

I see that the surface colors are changing based on their elevation. Is this a MUI V5 thing?
![image](https://user-images.githubusercontent.com/8997218/156821708-2312fdad-cb61-410f-b827-a878e95a44f2.png)

# 10
I saw these console errors
![image](https://user-images.githubusercontent.com/8997218/156822109-1ac02984-7727-49c5-934b-26ea14cc25d6.png)

# 11
Under 2x text size, the right score card's action row starts to misalign

![image](https://user-images.githubusercontent.com/8997218/156822374-11bcc549-f206-4e96-8d60-f7b9c8616ec8.png)

2022-03-07 12:25 UTC, ektasawant commented on src/blueDarkTheme.ts
> +                    height: 6,
after migrating to v5 , observed deleted code is not necessary. CSS must have fix in v5.

MUI v4:
<img width="417" alt="Screenshot 2022-03-07 at 5 52 58 PM" src="https://user-images.githubusercontent.com/10433274/157034090-2b267f5d-15b2-40ab-aa72-83d2c9abe3a3.png">

MUI v5:
<img width="424" alt="Screenshot 2022-03-07 at 5 52 49 PM" src="https://user-images.githubusercontent.com/10433274/157034118-81cb305f-2913-48bf-b5cd-b16c160a63ec.png">

2022-03-07 12:26 UTC, ektasawant commented
@joebochill , @huayunh will work on PR comments and update PR. Thanks for reviewing.

2022-03-16 11:48 UTC, ektasawant commented
@huayunh please check following:
**The theme transition and the input page seem to still eat up a lot of performance:**
It can be muiv5 issue. For reference https://github.com/mui/material-ui/discussions/29268. We can follow-up in another story.

1. **Error outlined select field sometimes get the wrong color**
Fixed
<img width="407" alt="Screenshot 2022-03-16 at 5 12 41 PM" src="https://user-images.githubusercontent.com/10433274/158582503-b1d65257-fdb3-449b-b452-2826e6dc8fb3.png">
 2 and 3 : Fixed RTL
 4:Fixed RTL
<img width="339" alt="Screenshot 2022-03-16 at 5 14 26 PM" src="https://user-images.githubusercontent.com/10433274/158582790-c923af8b-17c4-438b-bbc4-394f5c1065b8.png">
5. Fixed RTL
6. Will fix in another issue.
7.
<img width="429" alt="Screenshot 2022-03-16 at 5 16 17 PM" src="https://user-images.githubusercontent.com/10433274/158583124-1e3797cb-47ae-4416-977a-5571dc09c783.png">
8. 
<img width="829" alt="Screenshot 2022-03-16 at 5 16 57 PM" src="https://user-images.githubusercontent.com/10433274/158583215-1927ac9d-e252-43dc-8e87-b82b0de74900.png">
9. In muiv5 paper elevation having `background-image: linear-gradient(rgba(255, 255, 255, 0.07), rgba(255, 255, 255, 0.07)); `
<img width="1005" alt="Screenshot 2022-03-16 at 5 17 46 PM" src="https://user-images.githubusercontent.com/10433274/158583456-59bbae6f-7b25-4ff1-8f8a-4d02863677a6.png">
10. Fixed
11. Issue is exist in dev branch too. We can create issue for this.

2022-03-16 15:41 UTC, ektasawant commented on src/blueDarkTheme.ts
> +export const blueDarkTheme = createTheme({
Overriding works. Please review https://codesandbox.io/s/material-demo-forked-b1h8ps?file=/demo.js.

2022-03-16 15:41 UTC, ektasawant commented on src/blueTheme.ts
> +                    },
Removed. Please review.

2022-03-17 18:38 UTC, huayunh commented
I got 

> /Users/c3050144/Documents/repos/react-themes/node_modules/@mui/styled-engine/index.js
Module not found: Can't resolve '@emotion/react' in '/Users/c3050144/Documents/repos/react-themes/node_modules/@mui/styled-engine' 

When I tried running the project.

The row dividers in the table screenshot looks really dim.

Everything else looks fine from your screenshots.

2022-03-18 10:04 UTC, ektasawant commented
> The row dividers in the table screenshot looks really dim.

Divider color same as previous. It is looking dim because paper background.
![Uploading Screenshot 2022-03-18 at 3.33.38 PM.png…]()

For below error:
/Users/c3050144/Documents/repos/react-themes/node_modules/@mui/styled-engine/index.js
Module not found: Can't resolve '@emotion/react' in '/Users/c3050144/Documents/repos/react-themes/node_modules/@mui/styled-engine'

Did `yarn install` helped to fix this error?

2022-03-18 12:43 UTC, huayunh commented
The correct divider color in the dark theme should be black200 @ 36%. Is it using this color?

2022-03-18 16:39 UTC, ektasawant commented
> The correct divider color in the dark theme should be black200 @ 36%. Is it using this color?

Nope it was not having black200 @ 36%. Fixed it now.
<img width="1424" alt="Screenshot 2022-03-18 at 10 53 18 AM" src="https://user-images.githubusercontent.com/10433274/159045174-751d8c92-946b-458f-a457-36caf0babd56.png">

2022-03-21 15:28 UTC, ektasawant commented
> I got
> 
> > /Users/c3050144/Documents/repos/react-themes/node_modules/@mui/styled-engine/index.js
> > Module not found: Can't resolve '@emotion/react' in '/Users/c3050144/Documents/repos/react-themes/node_modules/@mui/styled-engine'
> 
> When I tried running the project.
> 
> The row dividers in the table screenshot looks really dim.
> 
> Everything else looks fine from your screenshots.

I tried following steps in react-themes:
1. cd demos/showcase and run `git checkout mui-v5`
2. Run `yarn start` .
3. It is working fine. Warning is known issue. https://github.com/styled-components/stylis-plugin-rtl/issues/33
<img width="924" alt="Screenshot 2022-03-21 at 8 56 45 PM" src="https://user-images.githubusercontent.com/10433274/159294300-e68af103-2d6f-4de8-ac00-781ebd4e8dc8.png">
t

2022-03-21 20:32 UTC, huayunh commented
Cool. The only thing I noticed was the chip border-color being off.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/8997218/159358771-09916ccc-73bf-4d09-9fe5-2a4742b42f02.png">

Figma:
<img width="504" alt="image" src="https://user-images.githubusercontent.com/8997218/159358628-6f95099d-c8b1-4d54-8a57-86a820258b11.png">

2022-03-21 20:40 UTC, huayunh commented
> cd demos/showcase and run git checkout mui-v5

The convention across all repos has been that one should be able to run yarn start from the root, without needing to cd, checkout and yarn install. Either some commands are not right, or a yarn update submodule is needed.

2022-03-22 14:16 UTC, huayunh commented
#36

2022-03-22 19:27 UTC, daileytj commented
It looks like there is an issue with `licence-checker` a peer-dependency of `npm-license-crawler`. There's a github link showing in the package.lock that doesn't satisfy the new URL schema github is using now. Not sure what the fix is yet.

2022-03-23 11:59 UTC, bkarambe requested changes

2022-03-23 11:59 UTC, bkarambe commented on CommonOverrides.md
> +import makeStyles from '@material-ui/core/styles/makeStyles';
This should be updated as:
import makeStyles from '@mui/styles/makeStyles';

2022-03-23 11:59 UTC, bkarambe commented on CHANGELOG.md
> -
Keep a blank line here for consistency.

2022-03-23 11:59 UTC, bkarambe commented on CHANGELOG.md
> +## v7.0.0 (Not yet published)
Here as well

2022-03-23 11:59 UTC, bkarambe commented on CHANGELOG.md
> +### Changed
Same

2022-03-23 11:59 UTC, bkarambe commented on CHANGELOG.md
> +-   Migration from Material UI v4 to v5. [#30](https://github.com/brightlayer-ui/react-themes/issues/30)
Changelog text should starts with ---> Updated/Fixed/Added.
Also leave a blank line after that.

2022-03-25 16:42 UTC, jeffvg commented
> 

@daileytj do you have an error or something with license checker?
I did fresh clone and installed then ran generate-license with no issues.
<img width="691" alt="image" src="https://user-images.githubusercontent.com/37150565/160163700-5ba8c921-a74f-4f68-baff-44dd820371ce.png">

yarn lock has this
<img width="794" alt="image" src="https://user-images.githubusercontent.com/37150565/160163843-6369bd88-8736-410f-a93d-87ca7ce1fee6.png">

2022-03-28 18:13 UTC, daileytj commented
> > 
> 
> @daileytj do you have an error or something with license checker? I did fresh clone and installed then ran generate-license with no issues. <img alt="image" width="691" src="https://user-images.githubusercontent.com/37150565/160163700-5ba8c921-a74f-4f68-baff-44dd820371ce.png">
> 
> yarn lock has this <img alt="image" width="794" src="https://user-images.githubusercontent.com/37150565/160163843-6369bd88-8736-410f-a93d-87ca7ce1fee6.png">

Must have been a temporary local issue. Looks good now

2022-03-28 18:59 UTC, bkarambe approved these changes

2022-03-28 19:00 UTC, merged